# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias umdq='ns:umdq'
alias md2yml-v1='umdq:md2yml-v1'
alias md2yml='umdq:md2yml'
umdq:install () 
{ 
    cargo install --git https://github.com/yshavit/mdq
}
umdq:md2yml () 
{ 
    local js='{"bash":"sh","json":"js","txt":"tt","sh":"tt"}';
    local jq='def item:
  .section as { $title, $body }
  | $body | map(.code_block // empty | { (.language | $map[.] // .): (.code / "\n") }) | add as $keys
  |  ($title / " ") | { type: .[0], id: .[1] } + { $keys };
def print:
  def id:
    def each:
      def yml: .value | map("  " + .);
      def others:[ "  \(.key): |-" ] + (.value | map("    " + .));
      if .key == "yml" then yml else others end;
      [ "- id: \(.id)" ] + (.keys | to_entries | map(each) | add);
  if .type == "raw" then .keys.yml else id end  | join("\n");
.items | map(item) | map(print) | join("\n\n")';
    mdq -o json '# /^(raw|id)/' | jq "$jq" -r --argjson map "$js"
}
umdq:md2yml-v1 () 
{ 
    local js='{"bash":"sh","json":"js","txt":"tt","sh":"tt"}';
    local jq='def item:
  .section | (.title / " ")[-1] as $id
  | .body | map(.code_block // empty | { (.language): .code }) | add as $keys
  | { $id } + $keys;
def filter: .items | map(item);
def head: first | if .id | test("^head") then .json | fromjson else [.] end;
def norm: with_entries(.key |= ($map[.] // .));
filter | head + .[1:] | map(norm)';
    mdq -o json '# /^(head|id)/' | jq "$jq" --argjson map "$js" | yq -P
}
umdq:src () 
{ 
    jq <<< '[{"ns":"umdq","id":"install","is":["na"],"sh":"cargo install --git https://github.com/yshavit/mdq"},{"ns":"umdq","id":"md2yml-v1","js":{"bash":"sh","json":"js","txt":"tt","sh":"tt"},"jq":"def item:\n  .section | (.title / \" \")[-1] as $id\n  | .body | map(.code_block // empty | { (.language): .code }) | add as $keys\n  | { $id } + $keys;\ndef filter: .items | map(item);\ndef head: first | if .id | test(\"^head\") then .json | fromjson else [.] end;\ndef norm: with_entries(.key |= ($map[.] // .));\nfilter | head + .[1:] | map(norm)","sh":"mdq -o json '\''# /^(head|id)/'\'' | jq \"$jq\" --argjson map \"$js\" | yq -P\n","tt":"< ssp.md md2yml-v1"},{"ns":"umdq","id":"md2yml","js":{"bash":"sh","json":"js","txt":"tt","sh":"tt"},"jq":"def item:\n  .section as { $title, $body }\n  | $body | map(.code_block // empty | { (.language | $map[.] // .): (.code / \"\\n\") }) | add as $keys\n  |  ($title / \" \") | { type: .[0], id: .[1] } + { $keys };\ndef print:\n  def id:\n    def each:\n      def yml: .value | map(\"  \" + .);\n      def others:[ \"  \\(.key): |-\" ] + (.value | map(\"    \" + .));\n      if .key == \"yml\" then yml else others end;\n      [ \"- id: \\(.id)\" ] + (.keys | to_entries | map(each) | add);\n  if .type == \"raw\" then .keys.yml else id end  | join(\"\\n\");\n.items | map(item) | map(print) | join(\"\\n\\n\")","sh":"mdq -o json '\''# /^(raw|id)/'\'' | jq \"$jq\" -r --argjson map \"$js\"\n","tt":"< ssp.md md2yml"}]'
}
ns:umdq () 
{ 
    umdq:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f umdq:install umdq:md2yml umdq:md2yml-v1 umdq:src ns:umdq
eval "$@"
